-- 核心四表：users、exam_records、question_details、exam_type_stats
-- 替换原 UUID users 及 V2 业务表（BIGINT 主键，适配 PostgreSQL / Supabase）
-- 说明：DATETIME → TIMESTAMPTZ，TINYINT → SMALLINT

-- ---------- 移除旧结构 ----------
DROP TABLE IF EXISTS ai_guidance_messages CASCADE;
DROP TABLE IF EXISTS ai_guidance_sessions CASCADE;
DROP TABLE IF EXISTS learning_stat_questions CASCADE;
DROP TABLE IF EXISTS learning_stat_sessions CASCADE;
DROP TABLE IF EXISTS paper_questions CASCADE;
DROP TABLE IF EXISTS papers CASCADE;
DROP TABLE IF EXISTS report_period_snapshots CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ---------- 1. 用户表 ----------
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT users_username_key UNIQUE (username),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE INDEX idx_users_email ON users (email);

COMMENT ON TABLE users IS '用户基本信息';
COMMENT ON COLUMN users.updated_at IS '更新时间，由应用层在修改时写入';

-- ---------- 2. 试卷上传与批改记录 ----------
CREATE TABLE exam_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    file_name VARCHAR(255) NOT NULL,
    file_url VARCHAR(500),
    status SMALLINT NOT NULL DEFAULT 0,
    total_questions INT NOT NULL DEFAULT 0,
    correct_count INT NOT NULL DEFAULT 0,
    accuracy_rate NUMERIC(5, 2),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT exam_records_status_check CHECK (status >= 0 AND status <= 4)
);

CREATE INDEX idx_exam_records_user_id ON exam_records (user_id);
CREATE INDEX idx_exam_records_created_at ON exam_records (created_at);

COMMENT ON TABLE exam_records IS '每次上传 PDF 并生成批改任务一条记录；含试卷级汇总便于按日聚合';
COMMENT ON COLUMN exam_records.status IS '0-待解析, 1-解析中, 2-AI批改中, 3-已完成, 4-失败';
COMMENT ON COLUMN exam_records.accuracy_rate IS '本卷正确率，如 85.50';

-- ---------- 3. 题目批改明细 ----------
CREATE TABLE question_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL REFERENCES exam_records (id) ON DELETE CASCADE,
    question_no INT NOT NULL,
    question_detail VARCHAR(255),
    question_type SMALLINT NOT NULL,
    user_answer VARCHAR(10),
    std_answer VARCHAR(10),
    is_correct SMALLINT NOT NULL,
    ai_analysis TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT question_details_is_correct_check CHECK (is_correct IN (0, 1))
);

CREATE INDEX idx_question_details_exam_id ON question_details (exam_id);
CREATE INDEX idx_question_details_question_type ON question_details (question_type);

COMMENT ON TABLE question_details IS '每道选择题的 AI 批改结果';
COMMENT ON COLUMN question_details.question_type IS '题型标识，如 1-推理, 2-材料分析（与业务枚举对齐）';
COMMENT ON COLUMN question_details.is_correct IS '1-正确, 0-错误';

-- ---------- 4. 试卷按题型汇总（AI 批改完成时写入）----------
CREATE TABLE exam_type_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL REFERENCES exam_records (id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    question_type SMALLINT NOT NULL,
    type_total_count INT NOT NULL DEFAULT 0,
    type_correct_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT exam_type_stats_exam_type_uq UNIQUE (exam_id, question_type)
);

CREATE INDEX idx_exam_type_stats_exam_id ON exam_type_stats (exam_id);
CREATE INDEX idx_exam_type_stats_user_id ON exam_type_stats (user_id);
CREATE INDEX idx_exam_type_stats_created_at ON exam_type_stats (created_at);

COMMENT ON TABLE exam_type_stats IS '单卷按题型汇总，冗余 user_id 加速按用户查询与按日统计';
