-- 本地 H2（profile=local）：与 V3 PostgreSQL 核心四表结构对齐（BIGINT 自增）
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(200) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL,
    age SMALLINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_username_key UNIQUE (username),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_age_range_check CHECK (age IS NULL OR (age >= 1 AND age <= 150))
);

CREATE INDEX idx_users_email ON users (email);

CREATE TABLE exam_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    file_name VARCHAR(255) NOT NULL,
    file_url VARCHAR(500),
    storage_bucket VARCHAR(64),
    storage_object_key VARCHAR(512),
    content_type VARCHAR(127),
    byte_size BIGINT,
    status SMALLINT NOT NULL DEFAULT 0,
    total_questions INT NOT NULL DEFAULT 0,
    correct_count INT NOT NULL DEFAULT 0,
    accuracy_rate NUMERIC(5, 2),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT exam_records_status_check CHECK (status >= 0 AND status <= 4)
);

CREATE INDEX idx_exam_records_user_id ON exam_records (user_id);
CREATE INDEX idx_exam_records_created_at ON exam_records (created_at);

CREATE TABLE question_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL REFERENCES exam_records (id) ON DELETE CASCADE,
    question_no INT NOT NULL,
    question_detail VARCHAR(255),
    -- 1=言语判断 2=数量关系 3=判断推理 4=资料分析 5=常识判断
    question_type SMALLINT NOT NULL,
    user_answer VARCHAR(10),
    std_answer VARCHAR(10),
    is_correct SMALLINT NOT NULL,
    ai_analysis CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT question_details_is_correct_check CHECK (is_correct IN (0, 1))
);

CREATE INDEX idx_question_details_exam_id ON question_details (exam_id);
CREATE INDEX idx_question_details_question_type ON question_details (question_type);

CREATE TABLE exam_type_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL REFERENCES exam_records (id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    -- 与 question_details.question_type 相同枚举
    question_type SMALLINT NOT NULL,
    type_total_count INT NOT NULL DEFAULT 0,
    type_correct_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT exam_type_stats_exam_type_uq UNIQUE (exam_id, question_type)
);

CREATE INDEX idx_exam_type_stats_exam_id ON exam_type_stats (exam_id);
CREATE INDEX idx_exam_type_stats_user_id ON exam_type_stats (user_id);
CREATE INDEX idx_exam_type_stats_created_at ON exam_type_stats (created_at);
